### ISSUE TITLE
Stremio mysteriously removed from apps listing

### ISSUE THREAD

**Issue by Ivshti** [electron/electron.atom.io#241]
Hello,

I noticed that on the new Electron website, all of the apps were there except ours - stremio.

Then I traced it down to this commit: https://github.com/electron/electron.atom.io/commit/9366efef0f9c24ceb12af9b25dabbd3e21cba05c#diff-89c586a35dec542f75a5988da1f868bd

Not only is Stremio one of the first apps that use Electron, probably one of the largest as well (1M+ sign-ups), but it also brought new developers to the Electron platform: https://github.com/electron/electron.atom.io/issues/187

I think someone should explain this.

**Comment by lee-dohm** [comment]
We removed the link to Stremio on advice from counsel. Unfortunately, we cannot comment further.

Thanks very much for reaching out.
