### ISSUE TITLE
Add criptio to the apps list

### ISSUE THREAD

**Issue by pmcalabrese** [electron/electron.atom.io#244]
I'd like to add Criptio to the apps list.
https://itunes.apple.com/us/app/criptio/id1102582966?mt=12. Would be ok?

**Comment by kevinsawicki** [comment]
@pmcalabrese sounds great as long as it is an Electron app and there aren't any issues using the icon.

See https://github.com/electron/electron.atom.io/blob/gh-pages/CONTRIBUTING.md#adding-an-app-or-project-to-the-site for more details.

**Comment by pmcalabrese** [comment]
@kevinsawicki great, but i cannot upload the icon, seems i need push permission also for create a branch ... :/

**Comment by kevinsawicki** [comment]
@pmcalabrese can you fork the repo and open a pull request from your fork?

**Comment by pmcalabrese** [comment]
@kevinsawicki ohh yee stupid me... i was in the clone.

**Comment by kevinsawicki** [comment]
This was fixed in #crip
