### ISSUE TITLE
Misleading advertising

### ISSUE THREAD

**Issue by alexandernst** [electron/electron.atom.io#25]
Electron's site announces the availability of features (auto-update for example) and only after reading the docs one realizes that those features are actually implemented only for X, Y or Z OS. Please fix (by adding side notes or `*`s) as you're misleading people and making them create wrong ideas about electron.

**Comment by 50Wliu** [comment]
I *think* this will be fixed by #75.

**Comment by 50Wliu** [comment]
@alexandernst Is this still relevant?

**Comment by alexandernst** [comment]
There are still features that electron supports only on certain platforms, but I think it's OK to close this.
