### ISSUE TITLE
Cannot upload my application icon to images/app folder

### ISSUE THREAD

**Issue by sabeehmurtaza9** [electron/electron.atom.io#312]
Cannot upload my application icon to images/app folder because when i open that folder for upload .. it shows me error that uploads disabled
![calculator_256](https://cloud.githubusercontent.com/assets/11147314/15628030/5965ba42-250f-11e6-8067-6aed71eedc86.png)

**Comment by kevinsawicki** [comment]
Can you clone the repo locally and add it via `git` and then push up the commit?

**Comment by sabeehmurtaza9** [comment]
Can you explain me the whole procedure?

**Comment by kevinsawicki** [comment]
@sabeehmurtaza9 you might want to read over https://help.github.com/articles/using-pull-requests/ for more information.
