### ISSUE TITLE
alt text is cut off if app description contains an apostrophe

### ISSUE THREAD

**Issue by zeke** [electron/electron.atom.io#342]
![screen shot 2016-06-13 at 10 47 21 am](https://cloud.githubusercontent.com/assets/2289/16017345/3d7ee60e-3154-11e6-9473-14c16ce65212.png)

`<a href='https://www.getflow.com' target='_blank' title='Flow - Task Management Software That Doesn't Feel Like Work' class='featured-app'>`

vi @as-cii

**Comment by jlord** [comment]
I'm working on it at this very moment 👍
