### ISSUE TITLE
Broken links tied to FAQ section located in different place on site and repo

### ISSUE THREAD

**Issue by jlord** [electron/electron.atom.io#364]
Porting this issue from https://github.com/electron/electron/issues/6328

This is because the FAQ page in the repository is located at `docs/faq/electron-faq` but for a nicer url on the site we changed it's permalink to `docs/faq`. So links within the docs linking to sections in the FAQ need to be found and updated. Or optionally, of course, we can make them located at the same path in both places. 

> I'm not sure how to fix this in the PR, so I'll just mention this.

> In the [Differences Between Main Process and Renderer Process](https://github.com/electron/electron/blob/master/docs/tutorial/quick-start.md#differences-between-main-process-and-renderer-process) part of the **Quick Start** there is a link to FAQ part [How to share data between web pages?](https://github.com/electron/electron/blob/master/docs/faq/electron-faq.md#how-to-share-data-between-web-pages). Inside GitHub docs it is OK. However, in the site doc the FAQ address differs and after the redirection the hash disappears, so a user just sees the top of the FAQ page. May be http://electron.atom.io/docs/faq/electron-faq#how-to-share-data-between-web-pages should be replaced by http://electron.atom.io/docs/faq/#how-to-share-data-between-web-pages there.

**Comment by zeke** [comment]
My vote would be to rename the file in the repo, which currently has a redundant path:

```
git mv docs/faq/electron-faq.md docs/faq.md
```

**Comment by jlord** [comment]
Fixed with the new version of docs 📖 ✨

**Comment by zeke** [comment]
✨ ❓ ✨
