### ISSUE TITLE
Some mess in the TOC pages

### ISSUE THREAD

**Issue by vsemozhetbyt** [electron/electron.atom.io#369]
1. The "API Reference" column in [the main TOC page](http://electron.atom.io/docs/) misses two docs mentioned in [the API TOC page](http://electron.atom.io/docs/api/): [Synopsis](http://electron.atom.io/docs/api/synopsis/) and [Possible Values of app.getLocale()](http://electron.atom.io/docs/api/app-locales/).

2. The resume cell of the "Possible Values of app.getLocale()" row in [the API TOC page](http://electron.atom.io/docs/api/) is out of the other cells style.

![1](https://cloud.githubusercontent.com/assets/10393198/16673489/4637022e-44b7-11e6-9dac-6fcf835e52ff.png)

**Comment by jlord** [comment]
Yikes! Thanks for reporting this @vsemozhetbyt! I've opened up an issue to fix it in the original docs cross-linked above ☝️

**Comment by jlord** [comment]
This is all fixed now ✨
