### ISSUE TITLE
Pagination on Apps Page

### ISSUE THREAD

**Issue by amitmerchant1990** [electron/electron.atom.io#503]
Hi Guys,

Here's a little suggestion. As the Electron is getting popular, the [app](http://electron.atom.io/apps/) of the site is also growing which is great! but the list is getting pretty long down the page. Can we implement the pagination here to solve the long scrolling? That would be handy I guess.

Hope to hearing from you guys soon.

UPDATE : We can implement something like [this](http://jsfiddle.net/fSmEL/167/).

Thanks,
Amit

**Comment by zeke** [comment]
Thanks for the suggestion, @amitmerchant1990. You're right that the page is getting a bit long. I personally would like to avoid using pagination until we have no other good options.

Another way we could address this is by using javascript to prevent app icons from downloading until they enter the viewport. This would keep the page payload size down without diminishing the user experience.

**Comment by amitmerchant1990** [comment]
@zeke Do you mean Lazy Loading here?

**Comment by zeke** [comment]
Yep. Something like this could do the trick:

https://github.com/toddmotto/echo
https://www.npmjs.com/package/echo-js

**Comment by amitmerchant1990** [comment]
Yes. That's perfect! 👍 However this is a good idea, I think the looong scrolling will still pertain even if we implement the lazy loading.

**Comment by zeke** [comment]
You're right. If we continue to feature user-submitted apps on the site, we'll eventually have to update the interface to be more useful. This could include displaying more information about each app, as well as enabling things like filtering, keywords, etc.

**Comment by amitmerchant1990** [comment]
Awesome! I can work upon these if you guys allows me to. :)

**Comment by zeke** [comment]
Working on reducing the footprint of the apps page: https://github.com/electron/electron-apps/pull/59

**Comment by zeke** [comment]
Hey @amitmerchant1990 we shipped [an update](https://github.com/electron/electron.atom.io/pull/654) last week that brought the cumulative icon filesizes from 6.6MB down to 1.5 MB.

This buys us more time. Eventually we may need to revise our rendering strategy for this page, but for now this fix seems adequate. Gonna close this out.

**Comment by amitmerchant1990** [comment]
Yes @zeke this layout looks really good as compared to the previous one where there were big images and apart from this user needed to hover over the app just look into the desc of it. Also, the search functionality is definitely a nice addition. Thanks!
