### ISSUE TITLE
Add Now.app

### ISSUE THREAD

**Issue by zeke** [electron/electron.atom.io#506]
👋  @leo and @rauchg

[Now.app](https://github.com/zeit/now-app) is nice! We'd love to feature it on the site. If you're game, please open a PR:

https://github.com/electron/electron.atom.io/blob/gh-pages/CONTRIBUTING.md#adding-an-app-or-project-to-the-site

**Comment by leo** [comment]
Sure, we'd love to be on the site! 👍 

@zeke Do you want me to set the `featuredOnHomepage` property? If so, which one do you want me to remove from the homepage (I'm assuming you don't want more than 5 rows)?

**Comment by zeke** [comment]
> Do you want me to set the `featuredOnHomepage` property?

Can you just leave it out for now? We'll get you featured on the homepage soon, one way or another.

**Comment by leo** [comment]
Sure! What else is needed for achieve this? Any conditions we need to comply with?

Here's the PR: https://github.com/electron/electron.atom.io/pull/511

**Comment by zeke** [comment]
✨ Merged! ✨ 

It'll be on the site in a moment, and we'll get it featured on the homepage soon. Thanks.
