### ISSUE TITLE
Link title missing

### ISSUE THREAD

**Issue by kevinsawicki** [electron/electron.atom.io#512]
The link title of `[MAS builds]` is being stripped away for a few links in the docs (it is showing just `docs/tutorial/mac-app-store-submission-guide` instead), probably a bug in the link parser.

http://electron.atom.io/docs/api/app/#appgetloginitemsettings-macos-windows

<img width="821" alt="screen shot 2016-10-05 at 9 29 12 am" src="https://cloud.githubusercontent.com/assets/671378/19122207/3e9b7fc8-8ade-11e6-980f-eff0ea8c1861.png">

**Comment by zeke** [comment]
This one seems to have ironed itself out. Must have been a fix in the doc itself.

![screen shot 2016-11-03 at 3 00 15 pm](https://cloud.githubusercontent.com/assets/2289/19987020/3deab0d0-a1d6-11e6-8488-8fbb569f3d84.png)
