### ISSUE TITLE
Blog feed contains invalid xml

### ISSUE THREAD

**Issue by ntns** [electron/electron.atom.io#515]
I cannot follow the electron blog because it contains invalid xml:

https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Felectron.atom.io%2Ffeed.xml

**Comment by Haacked** [comment]
Thanks for the report! It turns out it's due to a bug in jekyll-feed. I have an open PR there https://github.com/jekyll/jekyll-feed/pull/137

**Comment by ntns** [comment]
Thanks Phil!

**Comment by zeke** [comment]
It's valid now. Thanks for the fix, @Haacked 

<img width="586" alt="screen shot 2017-02-23 at 12 25 49 pm" src="https://cloud.githubusercontent.com/assets/2289/23277595/4380b9aa-f9c3-11e6-8472-6879ced82cd8.png">
