### ISSUE TITLE
Documentation lacking navigation options

### ISSUE THREAD

**Issue by mixmatch** [electron/electron.atom.io#54]
I see no way to navigate between all the pages in the documentation section. Instead of being able to simply go from API>Synopsis to API>Process Object, you have to go navigate back and forward to the main documentation page for every navigation. 
Possible suggestions:
- Use the 2/3 unused area on the sides of the documentation page to provide a navigation to go between different documentation pages.
- Make the directory tree useful with navigation links. If the top of the page reads "v0.28.0 / API / Synopsis", v0.28.0 should link to http://electron.atom.io/docs/v0.28.0/ and API to http://electron.atom.io/docs/v0.28.0/api/ (showing an appropriate section of the documentation).
- Make a single page version that eliminates the need for navigating back and forth to read through 
- Create links at the top and bottom of the page to go to previous and next sections of documentation

Discussion here:
https://discuss.atom.io/t/documentation-lacking-navigation-options/18042/2

**Comment by jlord** [comment]
Awesome, thanks for this feedback! We definitely want to make to make the docs as good as possible. 

The thing we're up against is growing code to manipulate the docs from their raw state (basic markdown files) on the Electron repository to be pages in Jekyll on the site. But some of this we maybe able to do with templating magic :tophat:

> Make a single page version that eliminates the need for navigating back and forth to read through

[electron.atom.io/docs/all](http://electron.atom.io/docs/all) :sparkles:

**Comment by jlord** [comment]
Checkout the new docs, they're much better now! http://electron.atom.io/docs/
