### ISSUE TITLE
Markdown reference links not properly parsed

### ISSUE THREAD

**Issue by zeke** [electron/electron.atom.io#541]
Links like this:

```
[MAS builds][mas-builds].
```

with reusable references like this:

```
[mas-builds]: ../tutorial/mac-app-store-submission-guide.md
```

Look like this on GitHub:

<img width="362" alt="screen shot 2016-10-24 at 8 38 27 pm" src="https://cloud.githubusercontent.com/assets/2289/19672296/0a332f28-9a2a-11e6-90d7-65d3b5d91e3f.png">

And like this on the website:

<img width="608" alt="screen shot 2016-10-24 at 8 40 17 pm" src="https://cloud.githubusercontent.com/assets/2289/19672305/1d57471a-9a2a-11e6-9dd5-874c380f3189.png">

with errant HTML like this:

```html
<p><strong>Note:</strong> This API has no effect on
docs/tutorial/mac-app-store-submission-guide.</p>
```

**Comment by kevinsawicki** [comment]
This looks like it might be a duplicate of https://github.com/electron/electron.atom.io/issues/512

**Comment by zeke** [comment]
Indeed it is. 🙈
