### ISSUE TITLE
Documentation: sometimes a long space appears between union type names

### ISSUE THREAD

**Issue by aliib** [electron/electron.atom.io#556]
For instance, the following md snippet code:
```
The `net` module has the following methods:

### `net.request(options)`

* `options` (Object | String) - The `ClientRequest` constructor options.
```
may be rendered as follows:
![image](https://cloud.githubusercontent.com/assets/22502062/19977490/0e96a92e-a1f4-11e6-8720-c41d93f146e2.png)

Related link: https://github.com/electron/electron/pull/7862

**Comment by kevinsawicki** [comment]
Looks like this is back.

<img width="929" alt="screen shot 2016-12-29 at 10 12 03 am" src="https://cloud.githubusercontent.com/assets/671378/21550514/5e9b5122-cdaf-11e6-8872-3a4598322fe0.png">

/cc @zeke  possibly a regression from #630?

Is this code still somewhere? https://github.com/electron/electron.atom.io/blob/06722407d888b89b4fbd65e6dc3ca4fc61dcd681/lib/doc-links.js#L128-L133

**Comment by zeke** [comment]
Yep. A regression. Sorry.

That code would need to be added back to the new `Doc` class: https://github.com/electron/electron.atom.io/blob/gh-pages/lib/doc.js
