### ISSUE TITLE
Documenting our Support Channels and Policies

### ISSUE THREAD

**Issue by zeke** [electron/electron.atom.io#557]
## The Problem

In responding to users on `electron/electron` issues, we are not consistent in our advice. Some maintainers tell users to join the Electron slack for help. Others tell users to visit the Atom/Electron discussion board. People sometimes tweet at us but we don't answer.

Our website is not currently very helpful either. There's nothing in the header or footer about support. The only thing we have now is buried in the homepage, far below the fold:

![screen shot 2016-11-03 at 2 03 14 pm](https://cloud.githubusercontent.com/assets/2289/19985185/bb4f4d0e-a1ce-11e6-9220-5fb0704d25b0.png)

## The Solution

I think we should add an `electron.atom.io/support` page that lists the various ways that Electron users can seek help from our team and the larger community. We should also outline an SLA here, so users know what to expect when they ask for help in one of these channels.

Having a single URL would be helpful for canned issue responses as well.

**Comment by MarshallOfSound** [comment]
FWIW I have a saved reply for those issues that tells them about both 😄 

> GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

I definitely think an obvious "Support" link in the top menu bar would be good 👍

**Comment by zeke** [comment]
Fixed by #642
