### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by DracotMolver** [electron/electron.atom.io#564]
Hi. How can I change the icon of my app (Soube) for a new one that I'm trying to add ?. Thanks

**Comment by zeke** [comment]
The basics:

- fork this repository
- in your fork, overwrite the icon file in question. You can do this on the master branch, or a feature branch if you like.
- git commit and git push
- open a pull request.

You can probably also accomplish all of this using the GitHub web interface.

Here's some info about how to open a pull request:

https://help.github.com/articles/creating-a-pull-request/

And here are some details about submitting apps to this repo:

https://github.com/electron/electron.atom.io/blob/gh-pages/CONTRIBUTING.md#adding-an-app-or-project-to-the-site

**Comment by zeke** [comment]
Oh I see you already opened a PR: https://github.com/electron/electron.atom.io/pull/560 -- we can get that sorted for you.

**Comment by zeke** [comment]
Do you want to use the dark version or the transparent version?

**Comment by DracotMolver** [comment]
oooh thankyou so much for the steps, I will save them as a bible :). Yes @zeke, I'd like the dark version :)
