### ISSUE TITLE
The build is breaking markdown links

### ISSUE THREAD

**Issue by zeke** [electron/electron.atom.io#624]
Noticed some funky stuff here https://github.com/electron/electron.atom.io/commit/ee8e01298be2678cb882461a43521a1ad829bb3c

<img width="1005" alt="screen shot 2016-12-13 at 3 55 28 pm" src="https://cloud.githubusercontent.com/assets/2289/21164235/b00d89c2-c14c-11e6-87d9-7a7035f60509.png">

**Comment by kevinsawicki** [comment]
Similar to #567?

**Comment by zeke** [comment]
Yup. Dupe of #567.
