### ISSUE TITLE
Phasing out redirects for old docs URLs

### ISSUE THREAD

**Issue by zeke** [electron/electron.atom.io#638]
The Jekyll server currently take about 20 seconds to start up. This is due in part to the [massive number of redirect files](https://raw.githubusercontent.com/electron/electron.atom.io/gh-pages/_docs/api/app.md) it has to generate for old docs URLs.

With redirects:

```sh
$ jekyll build && cd _site && tree | wc -l
9308
```

Without redirects:

```sh
$ jekyll build && cd _site && tree | wc -l
879
```

I checked Google Analytics to see what kind of traffic we are getting to these old URLs:

![screen shot 2016-12-21 at 12 13 47 pm](https://cloud.githubusercontent.com/assets/2289/21404757/94e8fe98-c777-11e6-9136-b7ba6e30145c.png)

Not a lot, but unfortunately I think it's too much traffic to justify removing the redirects just now.

**Comment by zeke** [comment]
It's now down to 0.26% of pageviews. That's 1 in 400.

Maybe that few enough now that we can pull the plug? I tend to think it's worth it, as it will [shave 8 seconds off Jekyll's build time](https://github.com/electron/electron.atom.io/issues/668). 🤔 

<img width="380" alt="screen shot 2017-02-21 at 6 22 08 pm" src="https://cloud.githubusercontent.com/assets/2289/23194389/afe14fae-f862-11e6-890f-9c13de08f5cd.png">

**Comment by kevinsawicki** [comment]
I'm fine removing the pre-1.0 redirects. At some point it would be great to be able to host all versions of the docs like Node does, https://nodejs.org/dist/

**Comment by db2k** [comment]
I would also remove the redirect and keep in mind to host the older docs later again.
