### ISSUE TITLE
Broken link to quick start on about page

### ISSUE THREAD

**Issue by zeke** [electron/electron.atom.io#646]
http://electron.atom.io/docs/tutorial/about has a link to `Quick Start Guide` that points to http://electron.atom.io/docs/quick-start, but it should be http://electron.atom.io/docs/quick-start

Works on GitHub, doesn't work on the website.

Originally filed here https://github.com/electron/electron/issues/8292

**Comment by 50Wliu** [comment]
I think you meant http://electron.atom.io/docs/tutorial/quick-start/ as the correct link.

**Comment by zeke** [comment]
Thanks @50Wliu!

This seems to have ironed itself out in the latest automated build. https://github.com/electron/electron.atom.io/commit/aaf50e7976d6687c1c75e3ecca4c66e19a8e43f1#diff-b2503848f2430cf9c4b374ea3edb3960
