### ISSUE TITLE
Add descriptions for the apps listed on website

### ISSUE THREAD

**Issue by tommorris** [electron/electron.atom.io#649]
The current [app listing](http://electron.atom.io/apps/) doesn't show the descriptions of what the apps do. The data is there but is invisible on the page. You have to hover over to see the descriptions. It would benefit potential users of Electron to be able to see the range of different things built with Electron rather than seeing just a list of somewhat enigmatic names and logos.

**Comment by zeke** [comment]
Totally agree. I will be working on this soon.

**Comment by zeke** [comment]
Hey @tommorris, this shipped! Take a look at http://electron.atom.io/apps/
