### ISSUE TITLE
https is not working

### ISSUE THREAD

**Issue by watilde** [electron/electron.atom.io#657]
The current site seems to be using the certificate of choosealicense.com
+ https://electron.atom.io/

**Comment by MarshallOfSound** [comment]
I believe this is a side-effect of using a sub-domain and GitHub Pages.  Not sure if there is even a solution to this while we are still on GitHub Pages

**Comment by zeke** [comment]
Suggestions in a recent meeting:

- Put a CDN in front of the existing GitHub Pages app
- Host it elsewhere, like Heroku or [Surge](https://surge.sh/)

**Comment by zeke** [comment]
Filed an issue with the Pages and Security teams. They're working on issuing a new cert.

**Comment by zeke** [comment]
Fixed! Thanks to @parkr for setting up the new cert.

![screen shot 2017-02-27 at 8 26 02 am](https://cloud.githubusercontent.com/assets/2289/23370242/f57b0a22-fcc8-11e6-985d-ddf9bf05eebd.png)

**Comment by zeke** [comment]
<img width="698" alt="screen shot 2017-02-27 at 8 53 52 am" src="https://cloud.githubusercontent.com/assets/2289/23371851/51dc7742-fcce-11e6-816a-f58c3360ccf9.png">
