### ISSUE TITLE
<webview> Tag listed twice

### ISSUE THREAD

**Issue by javan** [electron/electron.atom.io#658]
FYI!

<img width="314" alt="documentation_-_electron" src="https://cloud.githubusercontent.com/assets/5355/22157088/328cfdea-df04-11e6-933b-9d9e7ba26374.png">

**Comment by dkfiresky** [comment]
You can also find duplicated entry here: http://electron.atom.io/docs/api/

<img width="871" alt="screenshot 2017-01-23 at 22 15 35" src="https://cloud.githubusercontent.com/assets/2175645/22220969/9272faa4-e1b9-11e6-82fe-fcbccfea8eb1.png">
