### ISSUE TITLE
Apps: Add filter to filter by addition date

### ISSUE THREAD

**Issue by db2k** [electron/electron.atom.io#661]
Currently it's really hard to find out which app was added. I like coming by every 3-4 day to check if new electron apps came out, but since the github page uses the _data-folder this is not possible anymore.

Could we have a sort feature to sort by alphabet or addition date? I would love to have something like this, otherwise we have to check the history of the apps.json to see what was added.

**Comment by PterPmnta** [comment]
@db2k  I suggested that you add as a kind of icon to the icon of each application that refers that is new or uploaded that week

**Comment by db2k** [comment]
Either that or a simple dropdown for sorting by alphabet or by addition date.
I saw the dates are added to the app data again. Is it going to be added again?

**Comment by db2k** [comment]
I added a pullrequest (the lucky #700) which sorts the applist by release date so the latest apps are always on top. This would close this issue.

**Comment by db2k** [comment]
@zeke could you check my pull request?

**Comment by PterPmnta** [comment]
@db2k I hope @zeke  see you request soon

**Comment by db2k** [comment]
@zeke can we close this already?

**Comment by 50Wliu** [comment]
(protip: when creating PRs you can type `closes #661` in the description, and then when the PR is merged, the issue will be closed automagically!)
