### ISSUE TITLE
 How to know which apps are recently released

### ISSUE THREAD

**Issue by PterPmnta** [electron/electron.atom.io#663]
I would like to know how to identify the new applications published on the page, since previously the new applications simpr were at the end, and there was no such order as the alphabet.

I think the new organizational structure and the filter for doing fast searches are good but there is no identifier for the new ones.

I think that there should be some kind of warning, either next to the icon that identifies each application, more or less for the time of a week, so reconcoer which are the new applications.

**Comment by 50Wliu** [comment]
@kevinsawicki already opened an issue for you at #662.
