### ISSUE TITLE
Glossary not available

### ISSUE THREAD

**Issue by malept** [electron/electron.atom.io#674]
_(From a question on the Atom #electron Slack channel.)_

All of the glossary links 404, for example, http://electron.atom.io/docs/glossary#renderer-process. The markdown file exists in [electron/electron](https://github.com/electron/electron/blob/master/docs/glossary.md).

**Comment by zeke** [comment]
@sebcode fixed it in #689 

<img width="1027" alt="screen shot 2017-02-23 at 12 22 31 pm" src="https://cloud.githubusercontent.com/assets/2289/23277465/c657ea34-f9c2-11e6-8ddc-71e1f0633e52.png">
