### ISSUE TITLE
Permalink wraps to next link

### ISSUE THREAD

**Issue by kevinsawicki** [electron/electron.atom.io#72]
Super minor, feel free to close, just wanted to mention it since it looked a little strange.

http://electron.atom.io/docs/v0.30.0/api/dialog/

<img width="822" alt="screen shot 2015-08-13 at 9 05 06 am" src="https://cloud.githubusercontent.com/assets/671378/9254838/7fc0647a-419a-11e5-870d-84b061ae4ff8.png">

**Comment by jlord** [comment]
Dang. I guess this is where having them outside the left margin would be nice :/

**Comment by 50Wliu** [comment]
This isn't present on the latest version anymore (http://electron.atom.io/docs/latest/api/dialog/), though I don't suppose that means it's *fixed*.

**Comment by jlord** [comment]
I think we're ok to close for now and re-open if we start getting some long methods that wrap again 👍
