### ISSUE TITLE
How can I submit my electron app ?

### ISSUE THREAD

**Issue by Majaspic** [electron/electron.atom.io#721]
I didnt understood how

**Comment by vitorgalvao** [comment]
The [README for this repo is an instructions manual](https://github.com/electron/electron.atom.io#contributing).

Saying “I don’t understand how to do it” doesn’t help any one — you’ll just be directed to the guide. If want help, you need to be specific about which step you’re stuck on.

**Comment by zeke** [comment]
@Majaspic take a look at https://github.com/electron/electron-apps#adding-your-app -- there you'll find instructions for adding your app to the site.
