### ISSUE TITLE
Reverse tabnabbing fix is messing up referral analytics

### ISSUE THREAD

**Issue by zeke** [electron/electron.atom.io#732]
We've heard from some Electron app developers that their referral traffic from the Electron website has plummeted in the last month. It seems that #718 is the cause of the issues, as the `rel="noreferrer"` attribute disables the Referer HTTP header.

I think we can solve this by removing `noreferrer` from the `rel` attributes of our links, and leaving `noopener` in place.

cc @sarabreeding who reported this issue.
cc @CodeTheory who confirmed a drop in traffic for Kap.
cc @EdOverflow who submitted the original fix.

**Comment by CodeTheory** [comment]
You _could_ leave both `noreferrer` and `noopener` in place and using URL parameters instead. No sure how well that will work but it's a point for security.

**Comment by zeke** [comment]
Datapoint: [noopener](http://caniuse.com/#feat=rel-noopener) is supported by everything but Edge and IE, which constitutes <3% of sessions on electron.atom.io:

<img width="369" alt="screen shot 2017-05-11 at 4 08 22 pm" src="https://cloud.githubusercontent.com/assets/2289/25975628/49b458da-3664-11e7-9ca5-cf08942d5e73.png">

**Comment by zeke** [comment]
> using URL parameters instead

What would that entail?

**Comment by CodeTheory** [comment]
Using UTM parameters such as `?utm_source=electron.atom.io` etc. It would appear in Google analytics that the source would be electron.atom.io.

More here for anyone interested: https://blog.kissmetrics.com/how-to-use-utm-parameters/

Not sure if this covers all analytic services. Could be a solution though.

**Comment by sarabreeding** [comment]
I'm pretty familiar with UTM parameters, but I'm unsure if they will override `noreferrer`. Does `noreferrer` work the same as `noindex, nofollow` in terms of stopping Google from indexing and following links?

**Comment by bnb** [comment]
UTMs would mainly help with understanding the source of the traffic - but, like you said @sarabreeding, `noreferrer`will block indexing and therefore SEO benefits from that indexing. 

AFAIK no real way around this if `noreferrer` is enabled - only _easy_ solution is to just not use `target="_blank"`. That's not necessarily a bad option. That said, if it's no good, does anyone know of an alternative way to open in a new tab or way to sandbox this vulnerability? I'm not aware of one. 🤔

**Comment by zeke** [comment]
> not use `target="_blank"`

I'd be down with that.

**Comment by EdOverflow** [comment]
Another possible solution would be to use [blankshield](https://github.com/danielstjules/blankshield). Blankshield opens a hidden iframe which opens the new tab and then immediately removes the iframe.

**Comment by sarabreeding** [comment]
We are still unable to see referral data from the electron site. @zeke have you all decided if you're going to remove `target="_blank"` ?

**Comment by zeke** [comment]
@sarabreeding I think this is the most straightforward fix. I'll get it done today.
