### ISSUE TITLE
How to get current text selected in electron app?

### ISSUE THREAD

**Issue by tun-app** [electron/electron.atom.io#733]
I want to get current text selected in other application such as browser, editor ....
Example: when I use Keyboard shortcuts `ctrl+b` then in my electron application will open and get current text selected. pls help me!

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by tun-app** [comment]
Thank for your information ^^
