### ISSUE TITLE
Update webview tag docs to reflect changes made in electron/electron#9397

### ISSUE THREAD

**Issue by tonyganch** [electron/electron.atom.io#738]
https://github.com/electron/electron/pull/9397

**Comment by kevinsawicki** [comment]
Hi @tonyganch, sorry I misunderstood your question about this in slack, only the docs for stable releases are currently published to the site, so when 1.7.2 hits stable, the docs from that pull request will be automatically updated here, until then you can browse/read the 1.7.2 docs at https://github.com/electron/electron/tree/v1.7.2/docs

Apologies for the confusion, closing this out.
