### ISSUE TITLE
how to access the docs offline

### ISSUE THREAD

**Issue by zombieleet** [electron/electron.atom.io#742]
Grettings.

  I will like to access the docs offline, as a result of slow network in my country at times

**Comment by MarshallOfSound** [comment]
@zombieleet The docs website is generated from the markdown docs in the [electron/electron](https://github.com/electron/electron/tree/master/docs) repository.  If you want to read them offline you can just clone that repository and read the raw markdown docs 👍

**Comment by zombieleet** [comment]
@MarshallOfSound thanks, You are the best (Y)

**Comment by zeke** [comment]
✨ 🇳🇬 ✨ 

@zombieleet this might come in handy too: https://github.com/egoist/devdocs-app

(Someone recently added the Electron docs to it)

**Comment by zeke** [comment]
https://twitter.com/electronjs/status/874376980581437441

**Comment by zombieleet** [comment]
@Zeke thanks, and also thanks for the nigeria flag :+1:
